import type { RoadmapLevel } from './types';

/**
 * The full curriculum roadmap, shown in every level's sidebar so readers see
 * where the current level sits. Each level app marks its own level as active by
 * matching `level.level`; the other rows render as "planned/locked".
 */
export const ROADMAP: RoadmapLevel[] = [
  {
    level: 1,
    title: 'Fundamentals',
    concepts: [
      'Hydration',
      'Virtual DOM diffing complexity',
      'Event loop (macro vs microtasks)',
      'Critical rendering path',
      'Code splitting strategies',
      'Dynamic import chunking',
      'Preload vs Prefetch vs Preconnect',
      'CORS preflight',
      'CSRF vs XSS mitigation',
      'Web workers vs Service workers',
    ],
  },
  {
    level: 2,
    title: 'React Core & Rendering Mechanics',
    concepts: [
      'Reconciliation algorithm',
      'Fiber architecture',
      'Concurrent rendering',
      'Time slicing',
      'Scheduler priorities',
      'Suspense boundaries',
      'Selective hydration',
      'Server components',
      'Tearing in concurrent UI',
      'Stale closure problems',
    ],
  },
  {
    level: 3,
    title: 'Browser Performance',
    concepts: [
      'Layout thrashing',
      'Paint vs Layout vs Composite',
      'Browser compositing layers',
      'GPU acceleration in CSS',
      'CSS containment',
      'Render blocking resources',
      'Render waterfall',
      'Subpixel rendering',
      'Detached DOM nodes',
      'Garbage collection timing',
    ],
  },
  {
    level: 4,
    title: 'Advanced Data & State',
    concepts: [
      'Structural sharing',
      'Immutable data patterns',
      'Referential equality',
      'Memoization pitfalls',
      'Race conditions in UI state',
      'Finite state modeling',
      'Event sourcing in frontend',
      'Optimistic UI rollback',
      'Deterministic rendering',
      'Idempotent UI actions',
    ],
  },
  {
    level: 5,
    title: 'Caching & Networking',
    concepts: [
      'Cache invalidation strategies',
      'Stale-while-revalidate',
      'ETag vs Cache-control',
      'HTTP/3 and QUIC',
      'Backpressure in Streams API',
      'AbortController',
      'Streaming fetch response handling',
      'Priority hints',
      'SameSite cookie modes',
      'Speculative prerendering',
    ],
  },
  {
    level: 6,
    title: 'Security',
    concepts: [
      'CSP (Content Security Policy)',
      'Trusted Types',
      'DOM clobbering',
      'Prototype pollution',
      'Same-origin policy nuances',
      'Service Worker lifecycle traps',
      'SharedArrayBuffer',
      'Transferable objects',
      'CORS preflight internals',
      'Offline conflict resolution',
    ],
  },
  {
    level: 7,
    title: 'Web Platform Internals',
    concepts: [
      'Island architecture',
      'Partial hydration',
      'Streaming SSR',
      'Shadow DOM',
      'Custom elements lifecycle',
      'Web components interoperability',
      'IntersectionObserver internals',
      'ResizeObserver loop limits',
      'MutationObserver cost',
      'OffscreenCanvas',
    ],
  },
  {
    level: 8,
    title: 'Concurrency & Streams',
    concepts: [
      'Task starvation',
      'Priority inversion in async code',
      'Scheduler internals',
      'Concurrent rendering tearing',
      'Backpressure handling',
      'Streaming SSR pipelines',
      'WebRTC basics',
      'CRDT basics for collaboration',
      'Shared memory models',
      'Deterministic UI under async',
    ],
  },
];
